name: demo3

on:
  schedule:
    # runs every minute starting from minute 25 through 59.
    - cron:  '* * * * *'

# Cronjob syntax:
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *

jobs:
  Job_1:
    runs-on: ubuntu-latest
    env: 
      DAY_OF_WEEK: Mon
    steps:
      - name: Echo Hello
        run: |
          echo Hello!
      - name: Echo custom vars
        if: ${{ env.DAY_OF_WEEK == 'Mon' }}
        run: |
          echo "Webhook event: $GITHUB_EVENT_NAME"
          echo "Print DAY_OF_WEEK = $DAY_OF_WEEK"
          echo "Print DB hotst = $POSTGRES_HOST"
          echo "Print DB port = $POSTGRES_PORT"
        env:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
