name: demo1

on: [push]

jobs:
  demo1:
    runs-on: ubuntu-latest
    steps:
      # The uses keyword tells the job to retrieve v2 of the community action named actions/checkout@v2. 
      # This is an action that checks out your repository and downloads it to the runner, allowing you to run actions against your code (such as testing tools). 
      # You must use the checkout action any time your workflow will run against the repository's code or you are using an action defined in the repository.
      - name: Checkout repo
        uses: actions/checkout@v2
      # This step uses the actions/setup-node@v2 action to install the specified version of the node software package on the runner, 
      # which gives you access to the npm command.
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install node dependencies by running script
        run: ./.github/scripts/npm-install.sh
        shell: bash
      - name: Hello world action step
        id: hello
        # Here, after @, we can specify tag, SHAs or branch as indicator of which version to use.
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Darren Li'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  demo1-job2:
    runs-on: [ubuntu-latest]
    steps:
      - name: Write sth to a file
        run: |
          expr 1 + 1 > output.log
        shell: bash
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

          