# Reusable workflows must be placed in .github/worflows/ directory. 
# It doesn't work if we place Reusable workflows in any subdirectories below .github/worflows/ directory.
name: Reusable workflow example

on:
  # If this workflow is reusable, we need to place 'workflow_call' tag after 'on' tag.
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Echo defined vars
    runs-on: ubuntu-latest
    env:
      INPUT_USERNAME: ${{ inputs.username }}
      SECRET_TOKEN: ${{ secrets.token }}
    steps:
      - name: echo defined vars
        run: echo $INPUT_USERNAME $SECRET_TOKEN