name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Echo defined vars
    runs-on: ubuntu-latest
    env:
      INPUT_USERNAME: ${{ inputs.username }}
      SECRET_TOKEN: ${{ secrets.token }}
    steps:
      - name: echo defined vars
        run: echo $INPUT_USERNAME $SECRET_TOKEN